# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C50YzM_dOPmnXpc9LZuyl6qZL7QXjIeT
"""

import pandas as pd

# Create dataset
data = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Math': [85, 70, 95, 60],
    'Science': [90, 75, 85, 65],
    'English': [78, 80, 88, 70]
})

# Show dataset
data

# Calculate average score
data['Average'] = data[['Math','Science','English']].mean(axis=1)

# Show average scores
print(data[['Name','Average']])

# Top student
top_student = data.loc[data['Average'].idxmax()]
print("\nTop Student:")
print(top_student[['Name','Average']])

